"""
Build a small geoid undulation grid for a project bounding box.

The grid contains the per-cell offset (in meters) to ADD to a NAVD88
elevation to get a WGS84 ellipsoidal height. The runtime client uses
bilinear interpolation against this grid to position locations correctly
in 3D space.

Sourcing the geoid model is delegated to PROJ via pyproj. PROJ knows
which grid to use for any (lon, lat) — GEOID18 in CONUS, others elsewhere.
With network access, missing grids are fetched on demand from the PROJ CDN
and cached locally.

Usage:
    # Pull bbox from a tileset.json
    python build_geoid_subset.py \
      --bbox-from client/public/tiles/local/tileset.json \
      -o client/public/geoid/local.json

    # Specify bbox manually (west,south,east,north in degrees)
    python build_geoid_subset.py \
      --bbox -116.20,41.68,-116.10,41.72 \
      -o client/public/geoid/local.json

Notes:
- Grid spacing defaults to 1 arc-minute (~1.85km), matching GEOID18.
  Override with --spacing-arcmin if needed.
- The bbox is padded by ~2 grid cells so bilinear interpolation never
  falls off the edge for points inside the project area.
"""

import argparse
import json
from pathlib import Path

import numpy as np
import pyproj


def load_bbox_from_tileset(path: Path) -> tuple[float, float, float, float]:
    """Read west/south/east/north from a tileset.json's _extent_wgs84 field."""
    data = json.loads(path.read_text())
    extent = data.get("_extent_wgs84")
    if not extent:
        raise SystemExit(
            f"{path} has no _extent_wgs84 field — was it generated by tif_to_glb.py?"
        )
    return (extent["west"], extent["south"], extent["east"], extent["north"])


def parse_bbox_arg(arg: str) -> tuple[float, float, float, float]:
    parts = [float(x) for x in arg.split(",")]
    if len(parts) != 4:
        raise SystemExit("--bbox expects 'west,south,east,north'")
    return tuple(parts)  # type: ignore


def build_grid(west, south, east, north, spacing_deg, pad_cells):
    """Compute grid bounds + node coordinates with padding."""
    # Snap to grid spacing and pad
    w = (np.floor(west / spacing_deg) - pad_cells) * spacing_deg
    s = (np.floor(south / spacing_deg) - pad_cells) * spacing_deg
    e = (np.ceil(east / spacing_deg) + pad_cells) * spacing_deg
    n = (np.ceil(north / spacing_deg) + pad_cells) * spacing_deg

    nx = int(round((e - w) / spacing_deg)) + 1
    ny = int(round((n - s) / spacing_deg)) + 1

    lons = w + np.arange(nx) * spacing_deg
    lats = s + np.arange(ny) * spacing_deg

    return w, s, e, n, nx, ny, lons, lats


def compute_offsets(lons, lats):
    """
    For each (lon, lat) node, compute the geoid undulation:
        ellipsoidal_height - NAVD88_height
    Equivalent to: transform (lon, lat, 0) from EPSG:6349 to EPSG:4979 and
    return the resulting height.
    """
    # Enable network so PROJ can fetch any missing grids
    pyproj.network.set_network_enabled(True)

    transformer = pyproj.Transformer.from_crs(
        "EPSG:6349",  # NAD83(2011) + NAVD88 height (compound)
        "EPSG:4979",  # WGS84 lon/lat + ellipsoidal height
        always_xy=True,
    )

    lon_grid, lat_grid = np.meshgrid(lons, lats, indexing="xy")
    flat_lon = lon_grid.ravel()
    flat_lat = lat_grid.ravel()
    flat_h_in = np.zeros_like(flat_lon)

    _out_lon, _out_lat, out_h = transformer.transform(flat_lon, flat_lat, flat_h_in)
    offsets = np.asarray(out_h).reshape(lat_grid.shape)  # (ny, nx)

    return offsets


def main():
    parser = argparse.ArgumentParser(
        description="Build a small geoid undulation grid (NAVD88 → ellipsoidal)"
    )
    src = parser.add_mutually_exclusive_group(required=True)
    src.add_argument(
        "--bbox-from",
        type=Path,
        help="Path to a tileset.json with an _extent_wgs84 field",
    )
    src.add_argument(
        "--bbox",
        help="Manual bounding box: 'west,south,east,north' in degrees",
    )
    parser.add_argument(
        "-o", "--output", required=True, type=Path,
        help="Output JSON path (e.g. client/public/geoid/local.json)",
    )
    parser.add_argument(
        "--spacing-arcmin", type=float, default=1.0,
        help="Grid spacing in arc-minutes (default: 1.0, matches GEOID18)",
    )
    parser.add_argument(
        "--pad-cells", type=int, default=2,
        help="Extra cells around bbox so bilinear lookups never fall off",
    )
    parser.add_argument(
        "--model", default="GEOID18 (via PROJ)",
        help="Label for the geoid model (informational only)",
    )
    args = parser.parse_args()

    if args.bbox_from:
        west, south, east, north = load_bbox_from_tileset(args.bbox_from)
        print(f"Bbox from {args.bbox_from}: ({west:.4f}, {south:.4f}) → ({east:.4f}, {north:.4f})")
    else:
        west, south, east, north = parse_bbox_arg(args.bbox)
        print(f"Manual bbox: ({west:.4f}, {south:.4f}) → ({east:.4f}, {north:.4f})")

    spacing_deg = args.spacing_arcmin / 60.0
    w, s, e, n, nx, ny, lons, lats = build_grid(
        west, south, east, north, spacing_deg, args.pad_cells
    )
    print(f"Grid: {nx}x{ny} = {nx * ny} nodes at {args.spacing_arcmin}' spacing")
    print(f"Padded bbox: ({w:.4f}, {s:.4f}) → ({e:.4f}, {n:.4f})")

    print("Computing geoid offsets via pyproj/PROJ...")
    offsets = compute_offsets(lons, lats)
    print(f"  Offset range: {offsets.min():.3f} to {offsets.max():.3f} m")

    # Write as a flat array of records so DuckDB can read it as a table.
    # The runtime client derives bbox/spacing from MIN/MAX over this table.
    rows = []
    for row_idx in range(ny):
        for col_idx in range(nx):
            rows.append({
                "row_idx": int(row_idx),
                "col_idx": int(col_idx),
                "lon": round(float(lons[col_idx]), 8),
                "lat": round(float(lats[row_idx]), 8),
                "offset_m": round(float(offsets[row_idx, col_idx]), 4),
            })

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(rows))
    size_kb = args.output.stat().st_size / 1024
    print(f"\nWrote {args.output} ({size_kb:.1f} KB, {len(rows)} rows)")
    print(f"Model: {args.model}")


if __name__ == "__main__":
    main()
